//   Copyright (c) 2016 Ivan A Kostko (github.com/ivan-kostko)

//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at

//       http://www.apache.org/licenses/LICENSE-2.0

//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.


package main

import (
	"errors"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

var version = "1.0.1"

func init() {
	flag.Usage = func() {
		fmt.Fprintln(os.Stderr, "Usage of CodeGenerator:")
		fmt.Fprintln(os.Stderr, "")
		fmt.Fprintln(os.Stderr, "  CodeGenerator -pointer -type=<type> -template=<templateFile>")
		fmt.Fprintln(os.Stderr, "")
		fmt.Fprintln(os.Stderr, "version: ", version)
		flag.PrintDefaults()
	}

	flag.CommandLine.Init("", flag.ExitOnError)
}

func main() {
	typePointer := flag.Bool("pointer", false, "Determines whether a type is a pointer or not")
	typeName := flag.String("type", "", "Type fed to CodeGenerator")
	packageName := flag.String("package", "", "Package name")
    templateFile := flag.String("templateFile", "", "Template file name")

	flag.Parse()

	if *typeName == "" || *templateFile == "" {
		flag.Usage()
		return
	}

	pkgDir, err := packageDir(*packageName)
	if err != nil {
		panic(err)
	}

	outputFile := formatFileName(*typeName, *templateFile)
	writer, err := os.Create(filepath.Join(workingFolder, outputFile))
	if err != nil {
		panic(err)
	}
	defer writer.Close()

	generator := NewGenerator(*templateFile)

	m := getNewMetadata(*typeName, *typePointer, executionFolder)
	if err := generator.Generate(writer, m); err != nil {
		panic(err)
	}

	fmt.Printf("Generated by template %s %s\n", *templateFile, outputFile)
}

func formatFileName(typeName string, templateFileName string) string {
	return fmt.Sprintf("%s_%s.go", strings.ToLower(typeName), templateFileName)
}

func workingFolder() (string, error) {
    return os.Getwd()
}

func executionFolder() (string, error) {
    return filepath.Abs(filepath.Dir(os.Args[0]))
}
